server:
  port: 9090
debug: false

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers:
              - Authorization
              - Content-Type
              - Accept
              - Origin
              - X-Requested-With
              - X-Internal-Username
            allow-credentials: true
            exposed-headers:
              - Authorization
              - Access-Control-Allow-Origin
              - X-Internal-Username

      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**

        - id: main-service
          uri: http://main-service:8084
          predicates:
            - Path=/api/main/**

        - id: ws-service
          uri: ws://main-service:7070
          predicates:
            - Path=/ws, /ws/**


      discovery:
        locator:
          enabled: true